repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.29.0'  
    hooks:
    - id: yapf
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8 
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
     -  id: mypy
        args:
          - --ignore-missing-imports
        types: [file, python]
