# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py


# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: ./requirements.txt
    - requirements: ./.github/doc-requirements.txt

