version: '3.2'
services:

  # ICUBAM service
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: icubam
    container_name: icubam-server
    command: ./start_server.sh
    restart: unless-stopped
    tty: true
    ports:
      - "8888:8888"
    environment:
      ENV_MODE : "dev"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: ./resources/icubam-docker.env
        target: /home/icubam/resources/icubam.env
      - type: bind
        source: ./resources/icubam-docker.toml
        target: /home/icubam/resources/icubam.toml
      - type: bind
        source: ./resources/icubam.db
        target: /home/icubam/resources/icubam.db
      - type: bind
        source: ./resources/token.pickle
        target: /home/icubam/resources/token.pickle
    networks:
      - icubam-network

  # ICUBAM sms service
  app-sms:
    build:
      context: .
      dockerfile: Dockerfile
    image: icubam
    container_name: icubam-sms-server
    command: ./start_server_sms.sh
    restart: unless-stopped
    tty: true
    environment:
      ENV_MODE : "dev"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: ./resources/icubam-docker.env
        target: /home/icubam/resources/icubam.env
      - type: bind
        source: ./resources/icubam-docker.toml
        target: /home/icubam/resources/icubam.toml
      - type: bind
        source: ./resources/icubam.db
        target: /home/icubam/resources/icubam.db
      - type: bind
        source: ./resources/token.pickle
        target: /home/icubam/resources/token.pickle
    networks:
      - icubam-network

# Docker Networks
networks:
  icubam-network:
    driver: bridge
