version: '3.2'
services:

  # ICUBAM service
  app-server:
    build:
      context: "${ICUBAM_COMPOSE_CONTEXT:-.}"
      dockerfile: ./docker/Dockerfile
    image: "${IMAGE_NAME:-icubam}:${IMAGE_TAG:-latest}"
    container_name: icubam_www_server
    command: ./docker/start_server_www.sh
    restart: unless-stopped
    tty: true
    ports:
      - "8888:8888"
    environment:
      ICUBAM_CONFIG_FILE : "${ICUBAM_CONFIG_FILE:-icubam.toml}"
      SECRET_COOKIE : "$SECRET_COOKIE"
      JWT_SECRET : "$JWT_SECRET"
      GOOGLE_API_KEY : "$GOOGLE_API_KEY"
      TW_KEY : "$TW_KEY"
      TW_API : "$TW_API"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: "${ICUBAM_RESOURCES_PATH:-./resources}"
        target: /home/icubam/resources
      - type: bind
        source: ../icubam
        target: /home/icubam/icubam
      - type: bind
        source: ../scripts
        target: /home/icubam/scripts
    networks:
      - icubam-network

  # ICUBAM sms service
  app-sms:
    build:
      context: "${ICUBAM_COMPOSE_CONTEXT:-.}"
      dockerfile: ./docker/Dockerfile
    image: "${IMAGE_NAME:-icubam}:${IMAGE_TAG:-latest}"
    container_name: icubam_sms_server
    command: ./docker/start_server_sms.sh
    restart: unless-stopped
    tty: true
    environment:
      ICUBAM_CONFIG_FILE : "${ICUBAM_CONFIG_FILE:-icubam.toml}"
      SECRET_COOKIE : "$SECRET_COOKIE"
      JWT_SECRET : "$JWT_SECRET"
      GOOGLE_API_KEY : "$GOOGLE_API_KEY"
      TW_KEY : "$TW_KEY"
      TW_API : "$TW_API"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: "${ICUBAM_RESOURCES_PATH:-./resources}"
        target: /home/icubam/resources
      - type: bind
        source: ../icubam
        target: /home/icubam/icubam
      - type: bind
        source: ../scripts
        target: /home/icubam/scripts
    networks:
      - icubam-network

  # ICUBAM back-office service
  app-backoffice:
    build:
      context: "${ICUBAM_COMPOSE_CONTEXT:-.}"
      dockerfile: ./docker/Dockerfile
    image: "${IMAGE_NAME:-icubam}:${IMAGE_TAG:-latest}"
    container_name: icubam_bo_server
    command: ./docker/start_server_bo.sh
    restart: unless-stopped
    tty: true
    ports:
      - "8890:8890"
    environment:
      ICUBAM_CONFIG_FILE : "${ICUBAM_CONFIG_FILE:-icubam.toml}"
      SECRET_COOKIE : "$SECRET_COOKIE"
      JWT_SECRET : "$JWT_SECRET"
      GOOGLE_API_KEY : "$GOOGLE_API_KEY"
      TW_KEY : "$TW_KEY"
      TW_API : "$TW_API"
      DB_SALT: "$DB_SALT"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: "${ICUBAM_RESOURCES_PATH:-./resources}"
        target: /home/icubam/resources
      - type: bind
        source: ../icubam
        target: /home/icubam/icubam
      - type: bind
        source: ../scripts
        target: /home/icubam/scripts
    networks:
      - icubam-network


# Docker Networks
networks:
  icubam-network:
    driver: bridge
