name: Lint .tf files

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform-check:
    env:
      VERSION: "0.12.24"
      SHA256_HASH: "602d2529aafdaa0f605c06adb7c72cfb585d8aa19b3f4d8d189b42589e27bf11"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      run: |
        curl -fsSLO "https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip" && \
          echo "${SHA256_HASH}  terraform_${VERSION}_linux_amd64.zip" | sha256sum -c && \
          unzip "terraform_${VERSION}_linux_amd64.zip" && \
          sudo mv terraform /usr/local/bin && \
          rm -f "terraform_${VERSION}_linux_amd64.zip" && \
          terraform version
    - name: Run terraform fmt -check
      run: |
        terraform fmt -check -recursive || echo "Incorrectly formatted Terraform files. Please run: terraform fmt"
